install.packages('gsheet')
library(gsheet)
origData <- as.data.frame(gsheet2tbl('https://docs.google.com/spreadsheets/d/19-Zv4KiYXw20Dmtj97BfcE6Cri4paA2lnALa6H3w7pc/edit#gid=205206323'))
employeeID <- c(1:dim(origData)[1])
HRData<- as.data.frame(cbind(employeeID, origData))
colnames(HRData)[1] <- c('employee_ID')
